name: Postman API Tests with Local Server

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Project Dependencies
        run: |
          npm install

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Start Local Backend Server in Background
        run: |
          # Запускаем локальный сервер в фоне (убедись, что в package.json подстрока запуска называется 'start'. Если там другой скрипт, замени 'npm start' на 'npm run имя_скрипта')
          npm start &
          # Ждем 5 секунд, чтобы сервер успел поднять порт 3000 и инициализироваться
          sleep 5

      - name: Run Postman Tests via Newman
        run: |
          mkdir -p public
          newman run store.collection.json -r htmlextra --reporter-htmlextra-export public/index.html --reporter-htmlextra-darkTheme

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
